blog/urls.py
from django.urls import path

from blog.views import BlogPostListView, BlogPostDetailView, HomePageView

app_name = 'blog'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('blog/', BlogPostListView.as_view(), name='list'),
    path('blog/<int:pk>/', BlogPostDetailView.as_view(), name='detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('mailers.urls', namespace='mailers')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailers/urls.py
from django.urls import path

from mailers.apps import MailersConfig
from mailers.views import test_mail_view, new_app, SubscriberListView, SubscriberCreateView, SubscriberUpdateView, \
    SubscriberDeleteView, MailingListListView, MailingListCreateView, MailingListUpdateView, MailingListDeleteView, \
    MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, DistributionListView, \
    DistributionCreateView, DistributionUpdateView, DistributionDeleteView, DistributionLogListView

app_name = MailersConfig.name

urlpatterns = [
    path('subscribers/', SubscriberListView.as_view(), name='subscribers'),
    path('subscribers/new/', SubscriberCreateView.as_view(), name='subscriber_create'),
    path('subscribers/<int:pk>/edit/', SubscriberUpdateView.as_view(), name='subscriber_edit'),
    path('subscribers/<int:pk>/delete/', SubscriberDeleteView.as_view(), name='subscriber_delete'),
    path('mailing-lists/', MailingListListView.as_view(), name='mailing_lists'),
    path('mailing-lists/new/', MailingListCreateView.as_view(), name='mailing_list_create'),
    path('mailing-lists/<int:pk>/edit/', MailingListUpdateView.as_view(), name='mailing_list_edit'),
    path('mailing-lists/<int:pk>/delete/', MailingListDeleteView.as_view(), name='mailing_list_delete'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/new/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/edit/', MessageUpdateView.as_view(), name='message_edit'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('distributions/', DistributionListView.as_view(), name='distribution_list'),
    path('distributions/create/', DistributionCreateView.as_view(), name='distribution_create'),
    path('distributions/<int:pk>/edit/', DistributionUpdateView.as_view(), name='distribution_edit'),
    path('distributions/<int:pk>/delete/', DistributionDeleteView.as_view(), name='distribution_delete'),
    path('distributionslogs/', DistributionLogListView.as_view(), name='distributionlog_list'),
    path('test_mail/', test_mail_view, name='testmail'),
    path('app/', new_app, name='app'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import CustomLoginView, CustomSignupView, ActivateAccountView, CustomLogoutView

app_name = UsersConfig.name

urlpatterns = [
    path('sign-in/', CustomLoginView.as_view(), name='sign-in'),
    path('sign-up/', CustomSignupView.as_view(), name='sign-up'),
    path('activate/', ActivateAccountView.as_view(), name='activate'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

blog/models.py
from django.db import models


class BlogPost(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    image = models.ImageField(upload_to='blog_images/', null=True, blank=True)
    views = models.PositiveIntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']  # This will order posts by publication date in descending order

    def __str__(self):
        return self.title

blog/views.py
from random import sample

from django.core.cache import cache
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView

from blog.models import BlogPost
from mailers.models import Subscriber, Distribution


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blog/blogpost_list.html'
    context_object_name = 'blogposts'
    ordering = ['-pub_date']
    paginate_by = 12


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/blogpost_detail.html'
    context_object_name = 'blogpost'

    @method_decorator(cache_page(60 * 15))  # Кэширование страницы на 15 минут
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.views += 1
        self.object.save()
        return super().get(request, *args, **kwargs)


class HomePageView(View):
    template_name = 'blog/home_page.html'

    def get(self, request, *args, **kwargs):
        # Try to get parameters from the cache
        total_subscribers = cache.get('total_subscribers')
        total_mailings = cache.get('total_mailings')
        active_mailings = cache.get('active_mailings')

        # Calculate the required parameters if cashe is None
        if total_subscribers is None:
            total_subscribers = Subscriber.objects.values('email').distinct().count()
            cache.set('total_subscribers', total_subscribers)
        if total_mailings is None:
            total_mailings = Distribution.objects.count()
            cache.set('total_mailings', total_mailings)
        if active_mailings is None:
            active_mailings = Distribution.objects.filter(status=Distribution.Status.STARTED).count()
            cache.set('active_mailings', active_mailings)

        # Fetch three random articles from the blog
        all_blogposts = BlogPost.objects.all()
        random_blogposts = sample(list(all_blogposts), min(3, len(all_blogposts)))

        context = {
            'total_subscribers': total_subscribers,
            'total_mailings': total_mailings,
            'active_mailings': active_mailings,
            'blogposts': random_blogposts,
        }

        return render(request, self.template_name, context)

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>purrmail – dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/django_static/ico/purrmail_logo-bg.png" sizes="180x180">
    <link rel="icon" href="/django_static/ico/purrmail_logo-bg.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/django_static/ico/purrmail_logo-bg.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/django_static/ico/purrmail_logo.ico">
    <meta name="theme-color" content="#7952b3">



    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="/django_static/css/dashboard.css" rel="stylesheet">
</head>
<body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Purrmail{% if user.email %} | {{ user }}{% endif %}</a>
    <div class="navbar-nav">
        {% if user.email %}
        <div class="nav-item text-nowrap">
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="form-control form-control-dark px-3" type="submit">Sign out</button>
            </form>
        </div>
        {% else %}
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="{% url 'users:sign-in' %}">Sign in</a>
        </div>
<!--        <div class="nav-item text-nowrap">-->
<!--            <a class="nav-link px-3" href="{% url 'users:sign-up' %}">Sign up</a>-->
<!--        </div>-->
        {% endif%}
    </div>
</header>

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'blog:list' %}">
                            Our Blog
                        </a>
                    </li>
                    {% if user.email %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'mailers:subscribers' %}">
                            Subscribers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'mailers:mailing_lists' %}">
                            Mailing Lists
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'mailers:messages' %}">
                            Templates
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'mailers:distribution_list' %}">
                            Distributions
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'mailers:distributionlog_list' %}">
                            Distributions Logs
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'users:sign-in' %}">
                            Sign in
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'users:sign-up' %}">
                            Sign up
                        </a>
                    </li>

                    {% endif %}
                </ul>

            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            {% block content %}
            {% endblock %}
        </main>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
        crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/blogpost_detail.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container py-5">
    <h2>{{ blogpost.title }}</h2>
    <p>{{ blogpost.content }}</p>
    {% if blogpost.image %}
        <img src="{{ blogpost.image.url }}" alt="{{ blogpost.title }}" class="img-fluid">
    {% endif %}
    <p class="text-muted">Published on: {{ blogpost.pub_date }}</p>
    <div class="btn-group">
        <a href="{% url 'blog:list' %}" class="btn btn-sm btn-outline-secondary">Read News</a>
        <a href="{% url 'blog:index' %}" class="btn btn-sm btn-outline-secondary">Main Page</a>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="album py-5">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blogpost in blogposts %}
                <div class="col">
                    <div class="card shadow-sm">
                        {% if blogpost.image %}
                            <img src="{{ blogpost.image.url }}" alt="{{ blogpost.title }}" class="bd-placeholder-img card-img-top" width="100%" height="225" />
                        {% endif %}

                        <div class="card-body">
                            <h3>{{ blogpost.title }}</h3>
                            <p class="card-text">{{ blogpost.content|truncatechars:200 }}</p>
                            <p class="card-text"><small class="text-muted">{{ blogpost.views }} views</small></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'blog:detail' pk=blogpost.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                                </div>
                                <small class="text-muted">{{ blogpost.pub_date|date:"F d, Y" }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/home_page.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container py-5">
    <div class="row align-items-md-stretch">
        <div class="col-md-4">
            <div class="h-100 p-5 bg-light border rounded-3">
                <h2>{{ total_subscribers }}</h2>
                <p>Total number of unique subscribers of the service</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="h-100 p-5 bg-light border rounded-3">
                <h2>{{ total_mailings }}</h2>
                <p>Total number of total distributions</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="h-100 p-5 bg-light border rounded-3">
                <h2>{{ active_mailings }}</h2>
                <p>Total number of active distributions</p>
            </div>
        </div>
    </div>

</div>

<div class="album py-5">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blogpost in blogposts %}
            <div class="col">
                <div class="card shadow-sm">
                    {% if blogpost.image %}
                    <img src="{{ blogpost.image.url }}" alt="{{ blogpost.title }}" class="bd-placeholder-img card-img-top" width="100%" height="225" />
                    {% endif %}

                    <div class="card-body">
                        <h3>{{ blogpost.title }}</h3>
                        <p class="card-text">{{ blogpost.content|truncatechars:200 }}</p>
                        <p class="card-text"><small class="text-muted">{{ blogpost.views }} views</small></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blog:detail' pk=blogpost.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                            </div>
                            <small class="text-muted">{{ blogpost.pub_date|date:"F d, Y" }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}